// src/constants/errorCodes.js

// 用戶相關錯誤
export const USER_ERROR_CODES = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
    DISPLAY_NAME_REQUIRED: 'DISPLAY_NAME_REQUIRED',
    DISPLAY_NAME_TOO_LONG: 'DISPLAY_NAME_TOO_LONG',
    NO_FIELDS_TO_UPDATE: 'NO_FIELDS_TO_UPDATE'
};

// 密碼相關錯誤
export const PASSWORD_ERROR_CODES = {
    PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
    PASSWORD_INVALID_FORMAT: 'PASSWORD_INVALID_FORMAT',
    PASSWORD_SAME_AS_CURRENT: 'PASSWORD_SAME_AS_CURRENT'
};

// 通用錯誤
export const COMMON_ERROR_CODES = {
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

// 錯誤訊息映射
export const ERROR_MESSAGES = {
    // 用戶相關
    [USER_ERROR_CODES.USER_NOT_FOUND]: '用戶不存在，請重新登入',
    [USER_ERROR_CODES.INVALID_CURRENT_PASSWORD]: '目前密碼不正確，請重新輸入',
    [USER_ERROR_CODES.DISPLAY_NAME_REQUIRED]: '顯示名稱不能為空',
    [USER_ERROR_CODES.DISPLAY_NAME_TOO_LONG]: '顯示名稱長度不能超過50個字元',
    [USER_ERROR_CODES.NO_FIELDS_TO_UPDATE]: '沒有要更新的欄位',

    // 密碼相關
    [PASSWORD_ERROR_CODES.PASSWORD_TOO_SHORT]: '新密碼長度至少需要6個字元',
    [PASSWORD_ERROR_CODES.PASSWORD_TOO_LONG]: '新密碼長度不能超過100個字元',
    [PASSWORD_ERROR_CODES.PASSWORD_INVALID_FORMAT]: '新密碼必須包含英文字母和數字',
    [PASSWORD_ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: '新密碼不能與目前密碼相同',

    // 通用錯誤
    [COMMON_ERROR_CODES.MISSING_REQUIRED_FIELDS]: '請填寫所有必要欄位',
    [COMMON_ERROR_CODES.INTERNAL_SERVER_ERROR]: '系統錯誤，請稍後再試'
};

// 根據錯誤代碼獲取錯誤訊息
export const getErrorMessage = (errorCode, defaultMessage = '發生未知錯誤') => {
    return ERROR_MESSAGES[errorCode] || defaultMessage;
}; 