// src/constants/errorCodes.js

// 用戶相關錯誤
export const USER_ERROR_CODES = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
    DISPLAY_NAME_REQUIRED: 'DISPLAY_NAME_REQUIRED',
    DISPLAY_NAME_TOO_LONG: 'DISPLAY_NAME_TOO_LONG',
    DISPLAY_NAME_EMPTY: 'DISPLAY_NAME_EMPTY',
    NO_FIELDS_TO_UPDATE: 'NO_FIELDS_TO_UPDATE'
};

// 密碼相關錯誤
export const PASSWORD_ERROR_CODES = {
    PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
    PASSWORD_INVALID_FORMAT: 'PASSWORD_INVALID_FORMAT',
    PASSWORD_SAME_AS_CURRENT: 'PASSWORD_SAME_AS_CURRENT',
    WRONG_PASSWORD: 'WRONG_PASSWORD'
};

// 住戶相關錯誤
export const RESIDENT_ERROR_CODES = {
    RESIDENT_NOT_FOUND: 'RESIDENT_NOT_FOUND',
    RESIDENT_CODE_ALREADY_EXISTS: 'RESIDENT_CODE_ALREADY_EXISTS',
    RESIDENT_HAS_CHECKIN_DATA: 'RESIDENT_HAS_CHECKIN_DATA',
    CODE_ALREADY_EXISTS: 'CODE_ALREADY_EXISTS' // 舊版本相容
};

// 會議相關錯誤
export const MEETING_ERROR_CODES = {
    MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
    MEETING_ID_INVALID: 'MEETING_ID_INVALID',
    MEETING_SQM_THRESHOLD_INVALID: 'MEETING_SQM_THRESHOLD_INVALID',
    MEETING_RESIDENT_THRESHOLD_INVALID: 'MEETING_RESIDENT_THRESHOLD_INVALID',
    MEETING_DATE_INVALID: 'MEETING_DATE_INVALID',
    MEETING_STATUS_INVALID: 'MEETING_STATUS_INVALID',
    ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
    MEETING_NOT_MATCH: 'MEETING_NOT_MATCH'
};

// 社區相關錯誤
export const COMMUNITY_ERROR_CODES = {
    COMMUNITY_NOT_FOUND: 'COMMUNITY_NOT_FOUND',
    COMMUNITY_NAME_EMPTY: 'COMMUNITY_NAME_EMPTY',
    COMMUNITY_NAME_TOO_LONG: 'COMMUNITY_NAME_TOO_LONG',
    COMMUNITY_DESCRIPTION_EMPTY: 'COMMUNITY_DESCRIPTION_EMPTY',
    COMMUNITY_DESCRIPTION_TOO_LONG: 'COMMUNITY_DESCRIPTION_TOO_LONG',
    COMMUNITY_LOGO_URL_EMPTY: 'COMMUNITY_LOGO_URL_EMPTY',
    COMMUNITY_LOGO_URL_TOO_LONG: 'COMMUNITY_LOGO_URL_TOO_LONG',
    NO_UPDATE_FIELDS: 'NO_UPDATE_FIELDS'
};

// 認證相關錯誤
export const AUTH_ERROR_CODES = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS'
};

// 帳號/RBAC 相關錯誤
export const ACCOUNT_ERROR_CODES = {
    USERNAME_TAKEN: 'USERNAME_TAKEN',
    EMAIL_TAKEN: 'EMAIL_TAKEN',
    ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
    FORBIDDEN: 'FORBIDDEN',
    LAST_ADMIN_PROTECTED: 'LAST_ADMIN_PROTECTED',
    CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
    TARGET_USER_NOT_IN_COMMUNITY: 'TARGET_USER_NOT_IN_COMMUNITY',
    ROLE_INVALID: 'ROLE_INVALID',
};

// 通用錯誤
export const COMMON_ERROR_CODES = {
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    BAD_REQUEST: 'BAD_REQUEST'
};

// 錯誤訊息映射
export const ERROR_MESSAGES = {
    // 用戶相關
    [USER_ERROR_CODES.USER_NOT_FOUND]: '用戶不存在，請重新登入',
    [USER_ERROR_CODES.INVALID_CURRENT_PASSWORD]: '目前密碼不正確，請重新輸入',
    [USER_ERROR_CODES.DISPLAY_NAME_REQUIRED]: '顯示名稱不能為空',
    [USER_ERROR_CODES.DISPLAY_NAME_EMPTY]: '顯示名稱不能為空',
    [USER_ERROR_CODES.DISPLAY_NAME_TOO_LONG]: '顯示名稱長度不能超過50個字元',
    [USER_ERROR_CODES.NO_FIELDS_TO_UPDATE]: '沒有要更新的欄位',

    // 密碼相關
    [PASSWORD_ERROR_CODES.PASSWORD_TOO_SHORT]: '新密碼長度至少需要6個字元',
    [PASSWORD_ERROR_CODES.PASSWORD_TOO_LONG]: '新密碼長度不能超過100個字元',
    [PASSWORD_ERROR_CODES.PASSWORD_INVALID_FORMAT]: '新密碼必須包含英文字母和數字',
    [PASSWORD_ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: '新密碼不能與目前密碼相同',
    [PASSWORD_ERROR_CODES.WRONG_PASSWORD]: '密碼錯誤，請重新輸入',

    // 住戶相關
    [RESIDENT_ERROR_CODES.RESIDENT_NOT_FOUND]: '住戶不存在',
    [RESIDENT_ERROR_CODES.RESIDENT_CODE_ALREADY_EXISTS]: '此住戶戶號已被使用，請更換其他戶號',
    [RESIDENT_ERROR_CODES.CODE_ALREADY_EXISTS]: '此住戶戶號已被使用，請更換其他戶號',
    [RESIDENT_ERROR_CODES.RESIDENT_HAS_CHECKIN_DATA]: '此住戶已有簽到資料，無法刪除',

    // 會議相關
    [MEETING_ERROR_CODES.MEETING_NOT_FOUND]: '會議不存在',
    [MEETING_ERROR_CODES.MEETING_ID_INVALID]: '會議ID無效',
    [MEETING_ERROR_CODES.MEETING_SQM_THRESHOLD_INVALID]: '坪數門檻設定無效',
    [MEETING_ERROR_CODES.MEETING_RESIDENT_THRESHOLD_INVALID]: '戶數門檻設定無效',
    [MEETING_ERROR_CODES.MEETING_DATE_INVALID]: '會議時間設定無效',
    [MEETING_ERROR_CODES.MEETING_STATUS_INVALID]: '會議狀態設定無效',
    [MEETING_ERROR_CODES.ALREADY_CHECKED_IN]: '已經報到過，無需重複報到',
    [MEETING_ERROR_CODES.MEETING_NOT_MATCH]: '此QR碼屬於其他會議，無法在當前會議中使用',

    // 社區相關
    [COMMUNITY_ERROR_CODES.COMMUNITY_NOT_FOUND]: '社區不存在',
    [COMMUNITY_ERROR_CODES.COMMUNITY_NAME_EMPTY]: '社區名稱不能為空',
    [COMMUNITY_ERROR_CODES.COMMUNITY_NAME_TOO_LONG]: '社區名稱長度不能超過100個字元',
    [COMMUNITY_ERROR_CODES.COMMUNITY_DESCRIPTION_EMPTY]: '社區描述不能為空',
    [COMMUNITY_ERROR_CODES.COMMUNITY_DESCRIPTION_TOO_LONG]: '社區描述長度不能超過500個字元',
    [COMMUNITY_ERROR_CODES.COMMUNITY_LOGO_URL_EMPTY]: 'Logo URL不能為空',
    [COMMUNITY_ERROR_CODES.COMMUNITY_LOGO_URL_TOO_LONG]: 'Logo URL長度不能超過255個字元',
    [COMMUNITY_ERROR_CODES.NO_UPDATE_FIELDS]: '沒有要更新的欄位',

    // 認證相關
    [AUTH_ERROR_CODES.UNAUTHORIZED]: '未授權，請重新登入',
    [AUTH_ERROR_CODES.TOKEN_NOT_FOUND]: '認證失效，請重新登入',
    [AUTH_ERROR_CODES.INVALID_CREDENTIALS]: '帳號或密碼錯誤',

    // 通用錯誤
    [COMMON_ERROR_CODES.MISSING_REQUIRED_FIELDS]: '請填寫所有必要欄位',
    [COMMON_ERROR_CODES.INTERNAL_SERVER_ERROR]: '系統錯誤，請稍後再試',
    [COMMON_ERROR_CODES.INTERNAL_ERROR]: '系統錯誤，請稍後再試',
    [COMMON_ERROR_CODES.BAD_REQUEST]: '請求格式錯誤，請檢查輸入內容',

    // 帳號/RBAC 相關
    [ACCOUNT_ERROR_CODES.USERNAME_TAKEN]: '此使用者名稱已被使用',
    [ACCOUNT_ERROR_CODES.EMAIL_TAKEN]: '此 Email 已被使用',
    [ACCOUNT_ERROR_CODES.ACCOUNT_DEACTIVATED]: '此帳號已停用，請聯繫管理員',
    [ACCOUNT_ERROR_CODES.FORBIDDEN]: '權限不足',
    [ACCOUNT_ERROR_CODES.LAST_ADMIN_PROTECTED]: '社區必須至少保留一位啟用中的管理員',
    [ACCOUNT_ERROR_CODES.CANNOT_MODIFY_SELF]: '無法操作自己的帳號',
    [ACCOUNT_ERROR_CODES.TARGET_USER_NOT_IN_COMMUNITY]: '目標帳號不屬於你的社區',
    [ACCOUNT_ERROR_CODES.ROLE_INVALID]: '角色設定無效',
};

// 根據錯誤代碼獲取錯誤訊息
export const getErrorMessage = (errorCode, defaultMessage = '發生未知錯誤') => {
    return ERROR_MESSAGES[errorCode] || defaultMessage;
}; 